### ISSUE TITLE
can we get status response for particular Data Stream

### ISSUE THREAD

**Issue by hameedriswan7** [awsdocs/amazon-kinesis-data-streams-developer-guide#18]
i need particular status CREATING, ACTIVE, UPDATING, DELETING for Kinesis Data stream. 

i can get list of stream using this below code:

ListStreamsRequest listStreamsRequest = new ListStreamsRequest();
listStreamsRequest.setLimit(20); 
ListStreamsResult listStreamsResult = client.listStreams(listStreamsRequest);
List<String> streamNames = listStreamsResult.getStreamNames();

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
