### ISSUE TITLE
Add no Kinesis Data Analytics support to "when not to use the KPL"

### ISSUE THREAD

**Issue by chrisckchang** [awsdocs/amazon-kinesis-data-streams-developer-guide#2]
Currently, Kinesis Data Analytics doesn't support data generated by KPL (source: https://docs.aws.amazon.com/kinesisanalytics/latest/dev/limits.html).

Would it be appropriate to add a sentence on this to the "When Not To Use the KPL" section? https://github.com/awsdocs/amazon-kinesis-data-streams-developer-guide/blob/master/doc_source/developing-producers-with-kpl.md#when-not-to-use-the-kpl

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
