### ISSUE TITLE
Megabyte clarification

### ISSUE THREAD

**Issue by FrankChen021** [awsdocs/amazon-kinesis-data-streams-developer-guide#25]
> A single shard can ingest up to 1 MB of data per second (including partition keys) or 1,000 records per second for writes. Similarly, if you scale your stream to 5,000 shards, the stream can ingest up to 5 GB per second or 5 million records per second. If you need more ingest capacity, you can easily scale up the number of shards in the stream using the AWS Management Console or the UpdateShardCount API.
> 
> The maximum size of the data payload of a record before base64-encoding is up to 1 MB.

Does the `1 MB` above refer to `1 * 1000 * 1000` or `1 * 1024 * 1024` ?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
